GET http://localhost:3000


### FETCH SONGS REQUEST
GET http://localhost:3000/songs


### FIND SONGS REQUEST
GET http://localhost:3000/songs/1


### CREATE NEW SONGS REQUEST
POST http://localhost:3000/songs
Content-Type: application/json

{
  "title": "Lasting Lover",
  "artists": "Siagla",
  "releasedDate" : "2022-07-29 00:00:00",
  "duration" :"02:34"
}


### UPDATE SONGS REQUEST
PUT http://localhost:3000/songs/1


### DELETE SONGS REQUEST
DELETE http://localhost:3000/songs/1
# GET http://localhost:3000


# ? ============ VERSION 1 ==============
# ### FETCH SONGS REQUEST
# GET http://localhost:3000/songs


# ### FIND SONGS REQUEST
# GET http://localhost:3000/songs/1


# ### CREATE NEW SONGS REQUEST
# POST http://localhost:3000/songs
# Content-Type: application/json


# ### UPDATE SONGS REQUEST
# PUT http://localhost:3000/songs/1


# ### DELETE SONGS REQUEST
# DELETE http://localhost:3000/songs/1